# Generated by Django 2.2.13 on 2020-07-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('req_id', models.CharField(max_length=128)),
                ('video', models.CharField(max_length=256, null=True)),
                ('photo', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'Data',
            },
        ),
    ]
